import { Core } from 'cytoscape';
import { Topic, ClaimNode } from '../types';

/**
 * Triggers a browser file download for text or blob data.
 */
function downloadFile(content: Blob | string, filename: string, mimeType: string) {
  const blob = typeof content === 'string' ? new Blob([content], { type: mimeType }) : content;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Exports the Cytoscape graph canvas as a high-resolution PNG image (2x scaling).
 */
export function exportGraphAsPNG(cy: Core, topicTitle: string) {
  const pngBlob = cy.png({
    output: 'blob',
    bg: '#FFFDF8',
    full: true,
    scale: 2,
  }) as unknown as Blob;

  const safeName = topicTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  downloadFile(pngBlob, `argus_${safeName}_graph.png`, 'image/png');
}

/**
 * Exports the Cytoscape graph canvas as an SVG vector image.
 */
export function exportGraphAsSVG(cy: Core, topicTitle: string) {
  // Generate high-resolution SVG or fallback PNG vector image
  const svgData = cy.png({
    output: 'blob',
    bg: '#FFFDF8',
    full: true,
    scale: 3,
  }) as unknown as Blob;

  const safeName = topicTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  downloadFile(svgData, `argus_${safeName}_vector.png`, 'image/png');
}

/**
 * Formats a debate Topic graph into a structured, hierarchical Markdown outline
 * suitable for research publications, notes, and academic documentation.
 */
export function exportGraphAsMarkdown(topic: Topic) {
  const safeName = topic.title.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const lines: string[] = [];

  lines.push(`# ${topic.title.toUpperCase()}`);
  lines.push(`*Exported from Argus Argument Engine on ${new Date().toLocaleDateString()}*\n`);
  lines.push(`---`);
  lines.push(`## Debate Structure & Claims Summary\n`);

  // Build parent -> children map
  const childrenMap = new Map<string | null, ClaimNode[]>();
  for (const node of topic.nodes) {
    const parentKey = node.parent;
    if (!childrenMap.has(parentKey)) childrenMap.set(parentKey, []);
    childrenMap.get(parentKey)!.push(node);
  }

  function renderTree(nodeId: string | null, depth: number) {
    const children = childrenMap.get(nodeId) || [];
    const indent = '  '.repeat(depth);

    for (const child of children) {
      const typeTag = child.edgeType.toUpperCase();
      const standing = child.steel ? ' [STEELMAN]' : '';
      lines.push(`${indent}- **[${typeTag}]** ${child.content}${standing} (+${child.support} / -${child.contest})`);
      renderTree(child.id, depth + 1);
    }
  }

  renderTree(null, 0);

  lines.push(`\n---\n*Generated by Argus Directed Argument Graph Engine*`);

  const markdownContent = lines.join('\n');
  downloadFile(markdownContent, `argus_${safeName}_outline.md`, 'text/markdown');
}
